export enum Actions_E {
  CHANGE_STATUS_VALUE = "CHANGE_STATUS_VALUE",
  CHANGE_SPECIES_VALUE = "CHANGE_SPECIES_VALUE",
  CHANGE_GENDER_VALUE = "CHANGE_GENDER_VALUE",

  CHANGE_CURRENT_PAGE_VALUE = "CHANGE_CURRENT_PAGE_VALUE",

  SELECT_CHARACTER = "SELECT_CHARACTER",
}
