export enum Actions_E {
  CHANGE_STATUS_VALUE = 'CHANGE_STATUS_VALUE',
  CHANGE_SPECIES_VALUE = 'CHANGE_SPECIES_VALUE',
  CHANGE_GENDER_VALUE = 'CHANGE_GENDER_VALUE',

  GETTING_DATA = 'GETTING_DATA',

  SELECT_CHARACTER = 'SELECT_CHARACTER',
}
